// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jikaltfeyvxoepnftmuq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imppa2FsdGZleXZ4b2VwbmZ0bXVxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcxNDY0ODMsImV4cCI6MjA3MjcyMjQ4M30.glC7fRr-R5xLqvIRvyAmCebPO-gAUH6y1BC-f1bc-3k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    redirectTo: 'https://prelix.top'
  }
});